apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: devops-project
  namespace: argocd
spec:
  sourceRepos:
    - '*'
  destinations:
    - namespace: devops-playground
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
