groups:
  - name: k8s-alerts
    rules:
      - alert: HighCPUUsage
        expr: sum(rate(container_cpu_usage_seconds_total[2m])) by (pod) > 0.9
        for: 1m
        labels:
          severity: critical
        annotations:
          description: High CPU usage detected for pod {{ $labels.pod }}.
