global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'backend'
    static_configs:
      - targets: ['backend:5000']
  - job_name: 'frontend'
    static_configs:
      - targets: ['frontend:3000']
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

