version: '3.3'

services:
  database:
    image: mysql:8.0
    container_name: devops_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: devops_quiz
      MYSQL_USER: quizuser
      MYSQL_PASSWORD: quizpassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - devops_network

  backend:
    build:
      context: ../sample-app/backend
      dockerfile: Dockerfile
    container_name: devops_backend
    restart: always
    environment:
      DB_HOST: database
      DB_PORT: 3306
      DB_USER: quizuser
      DB_PASSWORD: quizpassword
      DB_NAME: devops_quiz
    ports:
      - "5000:5000"
    depends_on:
      - database
    networks:
      - devops_network

  frontend:
    build:
      context: ../sample-app/frontend
      dockerfile: Dockerfile
    container_name: devops_frontend
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - devops_network

volumes:
  db_data:

networks:
  devops_network:
