apiVersion: v1
kind: Service
metadata:
  name: jaeger
  namespace: monitoring
spec:
  selector:
    app: jaeger
  ports:
    - name: jaeger-ui
      port: 16686
      targetPort: 16686
    - name: jaeger-collector
      port: 14268
      targetPort: 14268
    - name: jaeger-zipkin
      port: 9411
      targetPort: 9411
  type: ClusterIP
