apiVersion: v1
kind: ConfigMap
metadata:
  name: db-init-config
data:
  init.sql: |
    CREATE TABLE records (
      id SERIAL PRIMARY KEY,
      name VARCHAR(100) NOT NULL,
      description TEXT NOT NULL,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );
