- hosts: localhost
  tasks:

    # Task 1: Apply Kubernetes configurations
    - name: Deploy application to Kubernetes
      command: kubectl apply -f ../kubernetes/
      register: deployment_output

    - name: Display deployment output
      debug:
        var: deployment_output.stdout_lines

    # Task 2: Check if backend pod is running
    - name: Check backend pod status
      shell: kubectl get pods -l app=backend -o jsonpath='{.items[0].status.phase}'
      register: backend_status
      retries: 5
      delay: 10
      until: backend_status.stdout == "Running"

    - name: Display backend health status
      debug:
        msg: "Backend pod is running and healthy"

    # Task 3: Fetch frontend service NodePort IP
    - name: Get frontend service NodePort IP
      shell: kubectl get svc frontend-service -o jsonpath='{.spec.ports[0].nodePort}'
      register: frontend_nodeport

    - name: Display frontend NodePort
      debug:
        msg: "Frontend is accessible on NodePort {{ frontend_nodeport.stdout }}"

    # Task 4: Display a time-based greeting
    - name: Get current time
      shell: date +%H
      register: current_hour

    - name: Display greeting based on time
      debug:
        msg: |
          {% if 5 <= current_hour.stdout|int < 12 %}
          Good morning! The application is up and running.
          {% elif 12 <= current_hour.stdout|int < 18 %}
          Good afternoon! The application is deployed successfully.
          {% elif 18 <= current_hour.stdout|int < 22 %}
          Good evening! Everything is set up and ready.
          {% else %}
          Good night! Your application is deployed and healthy.
          {% endif %}

